name: practice-jmeter-action
run-name: ${{ github.actor}} is practicing jmeter action
on: [push, pull_request]
jobs:
    run-jmeter-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Jmeter Test
              uses: QAInsights/PerfAction@v5.6.3
              with:
                  test-plan-path: Open_Model_Thread_Group.jmx
                  args: ""
            - name: Upload Results
              uses: actions/upload-artifact@v4
              with:
                  name: jmeter-results
                  path: result.jtl
                  if-no-files-found: error
