name: practice-k6-action
run-name: ${{ github.actor}} is practicing k6 action
on: [push, pull_request]
jobs:
    run-k6-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: grafana/setup-k6-action@v1.1.0
            - uses: grafana/run-k6-action@v1.3.1
              with:
                  path: |
                      test-script.js
