name: learn-github-actions
run-name: ${{ github.actor}} is learning github actions
on: [push, pull_request]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - run: npm install -g bats
            - run: bats -v
    run-k6-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: sudo gpg -k
            - run: sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
            - run: echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
            - run: sudo apt-get update
            - name: Install k6
              run: sudo apt-get install -y k6
            - name: Check k6 version
              run: k6 version
            - name: Run k6 script
              run: k6 run test-script.js
    run-jmeter-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "11"
            - name: Download Apache JMeter
              run: |
                  wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
                  tar -xvzf apache-jmeter-5.5.tgz
            - name: Jmeter Test
              uses: QAInsights/PerfAction@v5.6.3
              with:
                  test-plan-path: Open_Model_Thread_Group.jmx
                  args: ""
            - name: Upload Results
              uses: actions/upload-artifact@v4
              with:
                  name: jmeter-results
                  path: results.jtl
                  if-no-files-found: error
