name: learn-github-actions
run-name: ${{ github.actor}} is learning github actions
on: [push, pull_request]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
            - run: npm install -g bats
            - run: bats -v
    check-k6-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - run: sudo gpg -k
            - run: sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
            - run: echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
            - run: sudo apt-get update
            - run: sudo apt-get install -y k6
            - run: k6 version
    run-k6-test:
        runs-on: ubuntu-latest
        steps:
            - run: k6 run test-script.js
