name: learn-loadrunner-action
run-name: ${{ github.actor}} is learning loadrunner action
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            lrc_output_dir:
                description: "Directory to save LoadRunner Cloud results"
                required: false
                default: "./lrc_report"
jobs:
    run-loadrunner-script:
        runs-on: ubuntu-latest
        name: Start a load test
        steps:
            - name: Run test in LoadRunner Cloud
              uses: MicroFocus/lrc-gh-action@v1
              id: lrc_run_test
              env:
                  LRC_CLIENT_ID: ${{ secrets.LRC_CLIENT_ID }}
                  LRC_CLIENT_SECRET: ${{ secrets.LRC_CLIENT_SECRET }}
              with:
                  lrc_server: "https://loadrunner-cloud.saas.microfocus.com"
                  lrc_tenant: "756449080"
                  lrc_project: "1"
                  lrc_test_id: "1"
                  lrc_output_dir: lrc_report
                  lrc_report_types: "pdf"
            - name: Print test Run ID
              run: echo "Test Run ID is ${{ steps.lrc_run_test.outputs.lrc_run_id }}"
            - name: Updload LRC Results
              uses: actions/upload-artifact@v4
              with:
                  name: lrc-report-${{ steps.lrc_run_test.outputs.lrc_run_id}}
                  path: lrc_report
